# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    elasticsearch_client:
        class: Elastica\Client
        arguments:
            - "%elasticsearch_servers%"

